export const ActionTypes = {
  LOAD_DATA: "LOAD_DATA",
  API_ERROR: "API_ERROR",
  FETCH_All_PRODUCTS: "FETCH_All_PRODUCTS",
  FETCH_CATEGORY_PRODUCTS: "FETCH_CATEGORY_PRODUCTS",
  SORT_BY_ALPHABET: "SORT_BY_ALPHABET",
  SORT_BY_PRICE: "SORT_BY_PRICE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};
